# Generated by Django 5.2.7 on 2025-11-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zindo', '0003_remove_student_birthday_student_admission_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_year',
            new_name='admission_date',
        ),
    ]
