# Generated by Django 5.2.7 on 2025-12-08 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zindo", "0007_alter_sheet_is_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="학습일"
            ),
        ),
    ]
