# Generated by Django 6.0 on 2026-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zindo", "0008_alter_record_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화된 아동"),
        ),
    ]
