# Generated by Django 6.0.6 on 2026-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zindo", "0009_student_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="제목")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "student_ids",
                    models.JSONField(default=list, verbose_name="학생 ID 목록"),
                ),
                (
                    "student_newsletters",
                    models.JSONField(default=dict, verbose_name="개별 가정통신문"),
                ),
                (
                    "global_newsletter",
                    models.TextField(
                        blank=True, default="", verbose_name="전체 가정통신문"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
